FROM mcr.microsoft.com/devcontainers/go:1.22-bullseye as builder

ADD . /code
WORKDIR /code

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./bin/collector ./cmd/collector

FROM mcr.microsoft.com/cbl-mariner/distroless/minimal:2.0@sha256:450db4dc84c8c614f70d40abe5363d6788f50bc04221cb1d8437bb4d7753bd3f
COPY --from=builder /code/bin /

ENTRYPOINT ["/collector"]
