# Basic SummaryRule with Backfill Example
#
# This example shows a basic hourly aggregation rule that processes
# historical data from January 1-31, 2024, while continuing to process
# new data in real-time.

apiVersion: adx-mon.azure.com/v1
kind: SummaryRule
metadata:
  name: basic-backfill-example
  namespace: adx-mon
spec:
  database: Metrics
  table: HourlyMetricSummary
  body: |
    RawMetrics
    | where Timestamp between (_startTime .. _endTime)
    | summarize 
        avg_value = avg(Value),
        max_value = max(Value),
        min_value = min(Value),
        count = count()
      by bin(Timestamp, 1h), MetricName
  interval: 1h
  
  # Backfill configuration for historical data
  backfill:
    start: "2024-01-01T00:00:00Z"
    end: "2024-01-31T23:59:59Z"

---
# The system will:
# 1. Continue normal hourly processing of new data
# 2. Process historical data one hour at a time from Jan 1-31, 2024
# 3. Automatically advance the 'start' time after each successful window
# 4. Remove the entire 'backfill' field when complete
