---
apiVersion: adx-mon.azure.com/v1
kind: Function
metadata:
  name: collector-errors
  namespace: adx-mon
spec:
  database: Logs
  body: |
    .create-or-alter function CollectorErrors (period: timespan=1h) {
      Collector
      | where timestamp > ago(period)
      | where level == "ERR"
    }
