# permissions for end users to view alertrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: alertrule-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: adx-mon
    app.kubernetes.io/part-of: adx-mon
    app.kubernetes.io/managed-by: kustomize
  name: alertrule-viewer-role
rules:
- apiGroups:
  - adx-mon.azure.com
  resources:
  - alertrules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - adx-mon.azure.com
  resources:
  - alertrules/status
  verbs:
  - get
