---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - adx-mon.azure.com
  resources:
  - alertrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - adx-mon.azure.com
  resources:
  - alertrules/finalizers
  verbs:
  - update
- apiGroups:
  - adx-mon.azure.com
  resources:
  - alertrules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - adx-mon.azure.com
  resources:
  - events
  verbs:
  - create
  - patch
