FROM golang:1.20.4-bullseye as builder

ADD . /code
WORKDIR /code

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./bin/ingestor ./cmd/ingestor

FROM mcr.microsoft.com/cbl-mariner/distroless/minimal:2.0
COPY --from=builder /code/bin /

ENTRYPOINT /ingestor
